/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlantasRouteImport } from './routes/plantas'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as DatosRouteImport } from './routes/datos'
import { Route as CostosRouteImport } from './routes/costos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlantaPlantIdRouteImport } from './routes/planta.$plantId'

const PlantasRoute = PlantasRouteImport.update({
  id: '/plantas',
  path: '/plantas',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const DatosRoute = DatosRouteImport.update({
  id: '/datos',
  path: '/datos',
  getParentRoute: () => rootRouteImport,
} as any)
const CostosRoute = CostosRouteImport.update({
  id: '/costos',
  path: '/costos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantaPlantIdRoute = PlantaPlantIdRouteImport.update({
  id: '/planta/$plantId',
  path: '/planta/$plantId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/costos': typeof CostosRoute
  '/datos': typeof DatosRoute
  '/historico': typeof HistoricoRoute
  '/plantas': typeof PlantasRoute
  '/planta/$plantId': typeof PlantaPlantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/costos': typeof CostosRoute
  '/datos': typeof DatosRoute
  '/historico': typeof HistoricoRoute
  '/plantas': typeof PlantasRoute
  '/planta/$plantId': typeof PlantaPlantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/costos': typeof CostosRoute
  '/datos': typeof DatosRoute
  '/historico': typeof HistoricoRoute
  '/plantas': typeof PlantasRoute
  '/planta/$plantId': typeof PlantaPlantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/costos'
    | '/datos'
    | '/historico'
    | '/plantas'
    | '/planta/$plantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/costos'
    | '/datos'
    | '/historico'
    | '/plantas'
    | '/planta/$plantId'
  id:
    | '__root__'
    | '/'
    | '/costos'
    | '/datos'
    | '/historico'
    | '/plantas'
    | '/planta/$plantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CostosRoute: typeof CostosRoute
  DatosRoute: typeof DatosRoute
  HistoricoRoute: typeof HistoricoRoute
  PlantasRoute: typeof PlantasRoute
  PlantaPlantIdRoute: typeof PlantaPlantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plantas': {
      id: '/plantas'
      path: '/plantas'
      fullPath: '/plantas'
      preLoaderRoute: typeof PlantasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datos': {
      id: '/datos'
      path: '/datos'
      fullPath: '/datos'
      preLoaderRoute: typeof DatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costos': {
      id: '/costos'
      path: '/costos'
      fullPath: '/costos'
      preLoaderRoute: typeof CostosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planta/$plantId': {
      id: '/planta/$plantId'
      path: '/planta/$plantId'
      fullPath: '/planta/$plantId'
      preLoaderRoute: typeof PlantaPlantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CostosRoute: CostosRoute,
  DatosRoute: DatosRoute,
  HistoricoRoute: HistoricoRoute,
  PlantasRoute: PlantasRoute,
  PlantaPlantIdRoute: PlantaPlantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
